before_script:
  - make depend
build:
  script:
    - rm -rf /go/src/github.com/simonswine
    - mkdir -p /go/src/github.com/simonswine
    - mv ${CI_PROJECT_DIR} /go/src/github.com/simonswine
    - cd /go/src/github.com/simonswine/slingshot
    - make build_all
    - mv /go/src/github.com/simonswine/slingshot ${CI_PROJECT_DIR} 
  tags:
    - golang
  artifacts:
    paths:
      - _build/
