before_script:
  - make depend
build:
  script:
    - mkdir -p Godeps/_workspace/src/github.com/simonswine
    - ln -s $(pwd) Godeps/_workspace/src/github.com/simonswine/slingshot
    - make all
  tags:
    - golang
  artifacts:
    paths:
      - _build/
