before_script:
  - go get github.com/tools/godep
build:
  script:
    - mkdir -p Godeps/_workspace/src/github.com/simonswine
    - ln -s $(pwd) Godeps/_workspace/src/github.com/simonswine/slingshot
    - godep go build
    - godep go test -cover
  tags:
    - golang
